---
to: "<%= rootDir %>/factory.ts"
unless_exists: true
---
/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import { type ProcessorRecord } from "document-drive/processors/types";
import { type IProcessorHostModule } from "document-drive/processors/types";

// Import processor factories here as they are generated

export const processorFactory = (module: IProcessorHostModule) => {
  // Initialize all processor factories once with the module
  const factories: Array<(driveId: string) => ProcessorRecord[]> = [];
  
  // Add processors here as they are generated
  
  // Return the inner function that will be called for each drive
  return (driveId: string): ProcessorRecord[] => {
    const processors: ProcessorRecord[] = [];
    
    // Call each cached factory with the driveId
    for (const factory of factories) {
      processors.push(...factory(driveId));
    }
    
    return processors;
  };
}
