---
to: "<%= rootDir %>/factory.ts"
unless_exists: true
---
/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import { type ProcessorRecord } from "document-drive/processors/types";
import { type IProcessorHostModule } from "@powerhousedao/reactor-api";

// Import other processor factories here as they are generated

export const processorFactory = (module: IProcessorHostModule) => (driveId: string): ProcessorRecord[] => {
  const processors: ProcessorRecord[] = [];
  
  // Add all processor factories
  
  // Add other processors here as they are generated
  
  return processors;
}
