log_format lb_kv escape=json
    'time=$time_iso8601 '
    'remote_addr=$remote_addr '
    'method=$request_method '
    'uri=$uri '
    'status=$status '
    'request_time=$request_time '
    'upstream_addr=$upstream_addr '
    'upstream_response_time=$upstream_response_time '
    'doc_id=$doc_id '
    'request_id=$request_id';
