// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/src/lib/variables/processors/date-time.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone.js";
import utc from "dayjs/plugin/utc.js";
import type { ProcessorFn } from "./types.js";

export const dateTimeProcessor: ProcessorFn = (_property, value) => {
  dayjs.extend(utc);
  dayjs.extend(timezone);
  const dateTimeString = value;
  try {
    if (!dateTimeString) throw Error("Undefined input");
    return dayjs.tz(dateTimeString, "UTC").toISOString();
  } catch (error) {
    console.error(error);
    return undefined;
  }
};
