// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/src/lib/variables/processors/index.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import type { PropertyType } from "../../../../framework/index.js";
import { checkboxProcessor } from "./checkbox.js";
import { dateTimeProcessor } from "./date-time.js";
import { fileProcessor } from "./file.js";
import { jsonProcessor } from "./json.js";
import { multiSelectProcessor } from "./multi-select.js";
import { numberProcessor } from "./number.js";
import { objectProcessor } from "./object.js";
import { textProcessor } from "./text.js";
import type { ProcessorFn } from "./types.js";

export const processors: Partial<Record<PropertyType, ProcessorFn>> = {
  JSON: jsonProcessor,
  OBJECT: objectProcessor,
  NUMBER: numberProcessor,
  LONG_TEXT: textProcessor,
  SHORT_TEXT: textProcessor,
  SECRET_TEXT: textProcessor,
  DATE_TIME: dateTimeProcessor,
  FILE: fileProcessor,
  MULTI_SELECT_DROPDOWN: multiSelectProcessor,
  STATIC_MULTI_SELECT_DROPDOWN: multiSelectProcessor,
  CHECKBOX: checkboxProcessor,
};
