// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/src/lib/variables/processors/json.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import { isNil } from "../../../../core-utils/index.js";
import type { ProcessorFn } from "./types.js";

export const jsonProcessor: ProcessorFn = (_property, value) => {
  if (isNil(value)) {
    return value;
  }
  try {
    if (typeof value === "object") {
      return value;
    }
    return JSON.parse(value);
  } catch (error) {
    console.error(error);
    return undefined;
  }
};
