// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/src/lib/variables/processors/multi-select.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import { isNil, parseToJsonIfPossible } from "../../../../core-utils/index.js";
import type { ProcessorFn } from "./types.js";

export const multiSelectProcessor: ProcessorFn = (_property, value) => {
  if (isNil(value) || Array.isArray(value)) {
    return value;
  }
  if (typeof value === "string" && value.trim().length === 0) {
    return undefined;
  }
  const parsed = parseToJsonIfPossible(value);
  return Array.isArray(parsed) ? parsed : [value];
};
