// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/src/lib/variables/processors/number.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import { isNil } from "../../../../core-utils/index.js";
import type { ProcessorFn } from "./types.js";

export const numberProcessor: ProcessorFn = (_property, value) => {
  if (isNil(value)) {
    return value;
  }
  if (value === "") {
    return undefined;
  }
  return Number(value);
};
