// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/src/lib/variables/processors/object.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import { isNil } from "../../../../core-utils/index.js";
import type { ProcessorFn } from "./types.js";

export const objectProcessor: ProcessorFn = (_property, value) => {
  if (isNil(value)) {
    return value;
  }
  if (typeof value === "string") {
    try {
      return JSON.parse(value);
    } catch (e) {
      return undefined;
    }
  }
  if (typeof value === "object" && !Array.isArray(value)) {
    return value;
  }
  return undefined;
};
