// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/src/lib/variables/processors/text.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import { isNil } from "../../../../core-utils/index.js";
import type { ProcessorFn } from "./types.js";

export const textProcessor: ProcessorFn = (property, value) => {
  if (isNil(value)) {
    return value;
  }
  if (typeof value === "object") {
    return JSON.stringify(value);
  }

  const result = value.toString();
  if (result.length === 0 && !property.required) {
    return undefined;
  }
  return result;
};
