// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/src/lib/variables/processors/types.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.

/* eslint-disable @typescript-eslint/no-explicit-any */
import type { PieceProperty } from "../../../../framework/index.js";

export type ProcessorFn<INPUT = any, OUTPUT = any> = (
  property: PieceProperty,
  value: INPUT,
) => OUTPUT;
