name: Setup
description: Set up the required environment for running actions in the Powerhouse monorepo.
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org

    - name: Setup pnpm with cache
      uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: false

    - name: Setup bun global install
      uses: oven-sh/setup-bun@v2

    - name: Install with frozen lockfile
      shell: bash
      run: pnpm install-ci

    - name: Run typescript for the monorepo
      shell: bash
      run: pnpm build-tsc

    - name: Run css build scripts
      shell: bash
      run: pnpm build-css

    - name: Run vite build scripts
      shell: bash
      run: pnpm build-vite

    - name: Run misc build scripts
      shell: bash
      run: pnpm build-misc

