// @ts-check
import { default as eslint } from "@eslint/js";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import reactPlugin from "eslint-plugin-react";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.stylisticTypeChecked,
  ...tseslint.configs.strictTypeChecked,
  eslintPluginPrettierRecommended,
  {
    ignores: [
      "node_modules/",
      "dist/",
      "build/",
      "storybook-static/",
      "coverage/",
      "gen/",
      "docs/",
      "**/node_modules/",
      "**/dist/",
      "**/ts-dist/",
      "**/build/",
      "**/storybook-static/",
      "**/.storybook/",
      "**/coverage/",
      "**/gen/",
      "**/docs/",
      "**/browser.js",
      "**/src/assets/**/*",
      "**/postcss.config.js",
      "**/postcss.config.cjs",
      "**/postcss.config.mjs",
      "**/create-require.js",
      ".nx/",
      "packages/codegen/**/__tests__",
      "packages/document-drive/**/*.test.ts",
      "packages/document-drive/**/*.bench.ts",
      "packages/reactor-api/**/*.test.ts",
      "packages/reactor-api/**/*.bench.ts",
      "apps/connect/cypress/**/*.ts",
      "**/.vite/",
      "**/out/",
      "**/forge.config.js",
      "**/vite.config.ts.timestamp-*.mjs",
      "apps/connect/src/vite-env.d.ts",
      "apps/connect/src/external-packages.js",
      "**/*.config.*",
      "clis/ph-cli/.ph/",
      "packages/document-drive/src/storage/prisma/client/",
      "clis/ph-cli/test/utils.test.ts",
      "apps/connect/public/*.js",
    ],
  },
  {
    languageOptions: {
      sourceType: "module",
      ecmaVersion: "latest",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parserOptions: {
        projectService: {
          allowDefaultProject: ["vitest.workspace.ts"],
        },
        tsconfigRootDir: import.meta.dirname,
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/consistent-indexed-object-style": "off",
      "@typescript-eslint/no-duplicate-type-constituents": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        {
          prefer: "type-imports",
          fixStyle: "inline-type-imports",
        },
      ],
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/prefer-function-type": "off",
      "@typescript-eslint/strict-boolean-expressions": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-misused-promises": "off",
      "@typescript-eslint/prefer-reduce-type-parameter": "off",
      "@typescript-eslint/prefer-for-of": "off",
      "@typescript-eslint/require-await": "warn",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/unbound-method": "off",
      "@typescript-eslint/no-empty-object-type": "warn",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/prefer-find": "warn",
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
      "@typescript-eslint/restrict-plus-operands": "warn",
      "@typescript-eslint/return-await": "warn",
      "@typescript-eslint/no-dynamic-delete": "warn",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/no-unnecessary-condition": "warn",
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
      "@typescript-eslint/restrict-template-expressions": [
        "warn",
        {
          allowNumber: true,
        },
      ],
    },
  },
  {
    files: ["**/*.tsx"],
    ...reactPlugin.configs.flat.all,
    ...reactPlugin.configs.flat["jsx-runtime"],
    settings: {
      react: {
        version: "detect",
      },
    },
    plugins: {
      react: reactPlugin,
      "react-hooks": reactHooksPlugin,
    },
    rules: {
      "react/require-default-props": "off",
      "react/jsx-no-literals": "off",
      "react/forbid-component-props": "off",
      "react/no-multi-comp": "off",
      "react/destructuring-assignment": "off",
      "react/function-component-definition": "off",
      "react/prop-types": "off",
      "react/no-unused-prop-types": "warn",
      "react/jsx-max-depth": "off",
      "react/no-array-index-key": "off",
      "react/jsx-no-bind": "off",
      "react/button-has-type": "off",
      "react/hook-use-state": "off",
      "react/jsx-no-useless-fragment": "off",
      "react/jsx-props-no-spreading": "off",
    },
  },
);
