packages:
  - "apps/*"
  - "clis/*"
  - "packages/*"
  - "test/*"
  - "packages/reactor/test/atlas"
  - "scripts/*"
  - "shared"
  - "!releases"

catalog:
  "@powerhousedao/analytics-engine-core": 0.5.0
  "@powerhousedao/analytics-engine-graphql": 0.4.0
  "@powerhousedao/analytics-engine-pg": 0.6.0
  "@powerhousedao/document-engineering": 1.40.1
  "kysely": 0.28.11
  "kysely-pglite-dialect": 1.2.0
  "kysely-pglite": 0.6.1
  "kysely-knex": 0.2.0
  "@electric-sql/pglite": 0.3.15
  "@electric-sql/pglite-tools": 0.2.20
  "@electric-sql/pglite-react": 0.2.33
  "knex": 3.1.0
  "knex-pglite": 0.13.0
  "react": 19.2.4
  "react-dom": 19.2.4
  "@tailwindcss/vite": 4.1.18
  "@types/node": 25.2.3
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 5.1.4
  "graphql": 16.12.0
  "graphql-request": 7.4.0
  "vite": 7.3.1
  "vite-plugin-html": 3.2.2
  "vite-plugin-node-polyfills": 0.25.0
  "vite-plugin-svgr": 4.5.0
  "tailwindcss": 4.1.18
  "tailwind-merge": 3.4.0
  "@tailwindcss/cli": 4.1.18
  "zod": 4.3.6