packages:
  - "apps/*"
  - "clis/*"
  - "packages/*"
  - "test/*"
  - "packages/reactor/test/atlas"
  - "scripts/*"
  - "shared"
  - "!releases"

catalog:
  "@powerhousedao/analytics-engine-core": 0.5.0