/**
 * Regenerates the committed scalar catalog inventory.
 *
 *     pnpm exec tsx --conditions=source test/definition/regenerate-scalar-inventory.ts
 *
 * Tests never call it. The inventory is the catalog's published metadata —
 * every name, every per-definition digest, and the digest over the whole set —
 * and both the Node suite here and the browser suite in `reactor-browser`
 * check the catalog they construct against these exact bytes. It changes only
 * when someone runs this on purpose and reviews the diff.
 */
import { writeFileSync } from "node:fs";
import { scalarInventory } from "./scalar-inventory.js";

const header = [
  "// Generated by test/definition/regenerate-scalar-inventory.ts. Do not edit.",
  "//",
  "// The catalog's published metadata, as committed bytes. A module rather",
  "// than a .json file so both the Node suite here and the browser suite in",
  "// reactor-browser can import it without a loader or a file read.",
  'import type { ScalarInventory } from "../scalar-inventory.js";',
  "",
  "export const SCALAR_CATALOG_INVENTORY: ScalarInventory =",
].join("\n");

const path = new URL("./goldens/scalar-catalog-inventory.ts", import.meta.url);
writeFileSync(
  path,
  `${header} ${JSON.stringify(scalarInventory(), null, 2)} as const;\n`,
);
process.stdout.write(`wrote ${path.pathname}\n`);
