// The fixture reactor package: generated by the real `ph init`, given the one
// piece the suite runs, then built by `ph build` and published by `ph publish`.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { REGISTRY_URL, writeNpmrc } from "@powerhousedao/e2e-utils";

export const FIXTURE_PACKAGE = "test-workflow-piece-package";
export const FIXTURE_VERSION = "1.0.0";
export const FIXTURE_PIECE_DIR = "greeter";
export const FIXTURE_BLOCK_TYPE = `${FIXTURE_PACKAGE}#greet`;

export interface BuildFixtureOptions {
  /** The checked-in piece source, laid out as it sits in a package. */
  source: string;
  /** Directory `ph init` generates the project into. */
  parent: string;
  phCli: string;
  token: string;
  /** Dist-tag the workspace packages were published under. */
  tag: string;
}

export function run(
  command: string,
  args: string[],
  cwd: string,
  env?: NodeJS.ProcessEnv,
): void {
  console.log(`$ ${command} ${args.join(" ")}\n  (cwd=${cwd})`);
  execFileSync(command, args, {
    cwd,
    stdio: "inherit",
    env: { ...process.env, ...env },
  });
}

export interface BuiltFixture {
  dir: string;
  pieceDir: string;
  /** Piece package.json written by the build; proves the bundle is self-contained. */
  piecePackageJson: { name: string; version: string; dependencies: unknown };
  descriptor: { name: string; version: string; actions?: unknown };
  manifestPieces: { id: string; version: string; bundle: string }[];
}

function tagFlags(tag: string): string[] {
  if (tag === "dev") return ["--dev"];
  if (tag === "staging") return ["--staging"];
  if (tag === "rc") return ["--rc"];
  return ["--tag", tag];
}

export function buildAndPublishFixture(
  options: BuildFixtureOptions,
): BuiltFixture {
  const { source, parent, phCli, token, tag } = options;

  fs.rmSync(parent, { recursive: true, force: true });
  fs.mkdirSync(parent, { recursive: true });

  // `ph init` installs before a project .npmrc could exist, so the registry and
  // its token reach that install as npm's user config instead.
  writeNpmrc(parent, token);
  const env = { npm_config_userconfig: path.join(parent, ".npmrc") };

  run(
    phCli,
    ["init", FIXTURE_PACKAGE, "--pnpm", ...tagFlags(tag)],
    parent,
    env,
  );

  const dir = path.join(parent, FIXTURE_PACKAGE);
  writeNpmrc(dir, token);

  // Everything the piece needs around it — the stylesheet, the module entries,
  // the Tailwind toolchain, the pnpm workspace file — `ph init` already wrote.
  fs.cpSync(source, dir, { recursive: true });
  run(
    "pnpm",
    ["add", "--save-dev", `@powerhousedao/pieces-framework@${tag}`],
    dir,
    env,
  );

  // The project's own ph-cli, installed from the registry, so this is the build
  // a consumer of the release would run.
  run("pnpm", ["build"], dir, env);

  const pieceDir = path.join(dir, "dist/node/pieces", FIXTURE_PIECE_DIR);
  for (const file of ["index.mjs", "descriptor.json", "package.json"]) {
    const built = path.join(pieceDir, file);
    if (!fs.existsSync(built)) {
      throw new Error(`ph build did not write ${built}`);
    }
  }

  const piecePackageJson = JSON.parse(
    fs.readFileSync(path.join(pieceDir, "package.json"), "utf8"),
  ) as BuiltFixture["piecePackageJson"];
  const descriptor = JSON.parse(
    fs.readFileSync(path.join(pieceDir, "descriptor.json"), "utf8"),
  ) as BuiltFixture["descriptor"];
  const manifest = JSON.parse(
    fs.readFileSync(path.join(dir, "dist/powerhouse.manifest.json"), "utf8"),
  ) as { pieces?: BuiltFixture["manifestPieces"] };

  run(phCli, ["publish", "--registry", REGISTRY_URL], dir, env);

  return {
    dir,
    pieceDir,
    piecePackageJson,
    descriptor,
    manifestPieces: manifest.pieces ?? [],
  };
}
