import { ts } from "@tmpl/core";

export const processorsFactoryTemplate = () =>
  ts`
/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import type { 
  ProcessorRecord, 
  IProcessorHostModule, 
  ProcessorFactory,
} from "document-drive";
import type { PHDocumentHeader } from "document-model";
import type { ReactorContext } from "document-drive";

export const processorFactory = (module: IProcessorHostModule) => {
  // Initialize all processor factories once with the module
  const factories: Array<ProcessorFactory> = [];
  
  // Return the inner function that will be called for each drive
  return async (driveHeader: PHDocumentHeader, context?: ReactorContext): Promise<ProcessorRecord[]> => {
    const processors: ProcessorRecord[] = [];
    
    // Call each cached factory with the driveHeader
    for (const factory of factories) {
      const factoryProcessors = await factory(driveHeader);
      processors.push(...factoryProcessors);
    }
    
    return processors;
  };
}
`.raw;
