// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/test/piece-context/connection-resolver.test.ts. MIT; see ../../../../../pieces-framework/LICENSE.
// Generated by packages/pieces-framework/scripts/sync-upstream.mts — do not edit by hand.
import { ContextVersion } from "@powerhousedao/pieces-framework";
import {
  AppConnectionStatus,
  AppConnectionType,
} from "../../../upstream-adapters/shared.js";
import {
  createConnectionResolver,
  seedConnection,
} from "../../../upstream-adapters/connection-resolver.js";

const RESOLVER_PARAMS = {
  projectId: "project-123",
  apiUrl: "http://localhost:3000/",
  engineToken: "test-token",
  contextVersion: ContextVersion.V1,
};

function makeConnection({
  status = AppConnectionStatus.ACTIVE,
  type = AppConnectionType.SECRET_TEXT,
  value = { type: AppConnectionType.SECRET_TEXT, secret_text: "my-secret" },
  pieceName = "@activepieces/piece-slack",
}: {
  status?: AppConnectionStatus;
  type?: AppConnectionType;
  value?: Record<string, unknown>;
  pieceName?: string;
} = {}) {
  return {
    id: "conn-1",
    name: "my-connection",
    pieceName,
    status,
    value: { ...value, type },
  };
}

describe("connection-resolver service", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("V1 happy path returns connection.value", async () => {
    const connection = makeConnection();
    seedConnection(connection);

    const resolver = createConnectionResolver(RESOLVER_PARAMS);
    const result = await resolver.obtain("my-connection");

    expect(result).toEqual(connection.value);
  });

  // Known divergence (#3091): every piece gets the current context; getContextInfo is not read
  it.fails("V0 SECRET_TEXT returns connection.value.secret_text", async () => {
    const connection = makeConnection({
      type: AppConnectionType.SECRET_TEXT,
      value: { type: AppConnectionType.SECRET_TEXT, secret_text: "my-secret" },
    });
    seedConnection(connection);

    const resolver = createConnectionResolver({
      ...RESOLVER_PARAMS,
      contextVersion: undefined,
    });
    const result = await resolver.obtain("my-connection");

    expect(result).toBe("my-secret");
  });

  // Known divergence (#3091): every piece gets the current context; getContextInfo is not read
  it.fails("V0 CUSTOM_AUTH returns connection.value.props", async () => {
    const customProps = { apiKey: "abc", domain: "example.com" };
    const connection = makeConnection({
      type: AppConnectionType.CUSTOM_AUTH,
      value: { type: AppConnectionType.CUSTOM_AUTH, props: customProps },
    });
    seedConnection(connection);

    const resolver = createConnectionResolver({
      ...RESOLVER_PARAMS,
      contextVersion: undefined,
    });
    const result = await resolver.obtain("my-connection");

    expect(result).toEqual(customProps);
  });

  // Known divergence (#3091): OAuth2 connections are refused at run
  it.fails("V0 other types returns connection.value", async () => {
    const connection = makeConnection({
      type: AppConnectionType.OAUTH2,
      value: { type: AppConnectionType.OAUTH2, access_token: "tok" },
    });
    seedConnection(connection);

    const resolver = createConnectionResolver({
      ...RESOLVER_PARAMS,
      contextVersion: undefined,
    });
    const result = await resolver.obtain("my-connection");

    expect(result).toEqual(connection.value);
  });

  // Not applicable here: our ERROR status records a failed check; only REVOKED refuses a connection
  it.skip("throws ConnectionExpiredError when status is ERROR", async () => {
    const connection = makeConnection({ status: AppConnectionStatus.ERROR });
    seedConnection(connection);

    const resolver = createConnectionResolver(RESOLVER_PARAMS);
    await expect(resolver.obtain("my-connection")).rejects.toThrow();
  });
});

async function drainRetries<T>(pending: Promise<T>): Promise<T> {
  pending.catch(() => undefined);
  await vi.runAllTimersAsync();
  return pending;
}
