// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/test/piece-context/store.test.ts. MIT; see ../../../../../pieces-framework/LICENSE.
// Generated by packages/pieces-framework/scripts/sync-upstream.mts — do not edit by hand.
import { StoreScope } from "@powerhousedao/pieces-framework";
import {
  STORE_KEY_MAX_LENGTH,
  STORE_VALUE_MAX_SIZE,
} from "../../../upstream-adapters/shared.js";
import {
  createContextStore,
  lastStoreCall,
  seedStoreEntry,
} from "../../../upstream-adapters/store.js";

const STORE_PARAMS = {
  apiUrl: "http://localhost:3000/",
  prefix: "test_",
  flowId: "flow-123",
  engineToken: "test-token",
};

describe("store service", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  describe("createContextStore get()", () => {
    it("returns value when store entry exists", async () => {
      const storeEntry = {
        key: "test_flow_flow-123/myKey",
        value: { foo: "bar" },
      };
      await seedStoreEntry(storeEntry, STORE_PARAMS);

      const store = createContextStore(STORE_PARAMS);
      const result = await store.get("myKey");

      expect(result).toEqual({ foo: "bar" });
    });

    it("returns null when store entry is not found (404)", async () => {
      vi.spyOn(global, "fetch").mockResolvedValue(
        new Response(null, { status: 404 }),
      );

      const store = createContextStore(STORE_PARAMS);
      const result = await store.get("missingKey");

      expect(result).toBeNull();
    });

    it("throws StorageInvalidKeyError for empty key", async () => {
      const store = createContextStore(STORE_PARAMS);
      await expect(store.get("")).rejects.toThrow();
    });

    // Not applicable here: a store call is a host call, not HTTP, so there is no status to map
    it.skip("throws StorageError on server 500", async () => {
      vi.spyOn(global, "fetch").mockResolvedValue(
        new Response("Internal Server Error", { status: 500 }),
      );

      const store = createContextStore(STORE_PARAMS);
      await expect(store.get("myKey")).rejects.toThrow();
    });

    // Known divergence (README: ctx.store key length): only a put checks the key length (assertPieceStoreEntry); get and delete do not
    it.fails("throws StorageInvalidKeyError when key exceeds max length", async () => {
      const store = createContextStore(STORE_PARAMS);
      const longKey = "a".repeat(STORE_KEY_MAX_LENGTH + 1);
      await expect(store.get(longKey)).rejects.toThrow();
    });
  });

  describe("createContextStore put()", () => {
    it("puts value and returns it", async () => {
      const storeEntry = { key: "test_flow_flow-123/myKey", value: "hello" };
      await seedStoreEntry(storeEntry, STORE_PARAMS);

      const store = createContextStore(STORE_PARAMS);
      const result = await store.put("myKey", "hello");

      expect(result).toBe("hello");
    });

    it("throws StorageLimitError when value exceeds max size (no fetch call)", async () => {
      const fetchSpy = vi.spyOn(global, "fetch");
      const largeValue = "x".repeat(STORE_VALUE_MAX_SIZE + 1);

      const store = createContextStore(STORE_PARAMS);
      await expect(store.put("myKey", largeValue)).rejects.toThrow();
      expect(fetchSpy).not.toHaveBeenCalled();
    });

    // Not applicable here: a store call is a host call, not HTTP; the size ceiling is the case above
    it.skip("throws StorageLimitError on 413 response", async () => {
      vi.spyOn(global, "fetch").mockResolvedValue(
        new Response(null, { status: 413 }),
      );

      const store = createContextStore(STORE_PARAMS);
      await expect(store.put("myKey", "small value")).rejects.toThrow();
    });
  });

  describe("createContextStore delete()", () => {
    it("deletes entry and returns void", async () => {
      vi.spyOn(global, "fetch").mockResolvedValue(
        new Response(null, { status: 200 }),
      );

      const store = createContextStore(STORE_PARAMS);
      await expect(store.delete("myKey")).resolves.toBeUndefined();
    });

    it("throws StorageInvalidKeyError for empty key", async () => {
      const store = createContextStore(STORE_PARAMS);
      await expect(store.delete("")).rejects.toThrow();
    });
  });

  describe("key scoping", () => {
    it("FLOW scope prefixes key with flow id", async () => {
      const fetchSpy = vi.spyOn(global, "fetch").mockResolvedValue(
        new Response(JSON.stringify({ key: "k", value: null }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );

      const store = createContextStore(STORE_PARAMS);
      await store.get("myKey", StoreScope.FLOW);

      // Ours partitions by (scope, flow) instead of prefixing the key.
      expect(fetchSpy).not.toHaveBeenCalled();
      expect(lastStoreCall()).toEqual({
        scope: "FLOW",
        scopeKey: "flow-123",
        key: "myKey",
      });
    });

    it("PROJECT scope prefixes key without flow id", async () => {
      const fetchSpy = vi.spyOn(global, "fetch").mockResolvedValue(
        new Response(JSON.stringify({ key: "k", value: null }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );

      const store = createContextStore(STORE_PARAMS);
      await store.get("myKey", StoreScope.PROJECT);

      // Ours partitions by (scope, flow) instead of prefixing the key.
      expect(fetchSpy).not.toHaveBeenCalled();
      expect(lastStoreCall()).toEqual({
        scope: "PROJECT",
        scopeKey: "reactor",
        key: "myKey",
      });
    });

    it("default scope is FLOW", async () => {
      const fetchSpy = vi.spyOn(global, "fetch").mockResolvedValue(
        new Response(JSON.stringify({ key: "k", value: null }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );

      const store = createContextStore(STORE_PARAMS);
      await store.get("myKey");

      // Ours partitions by (scope, flow) instead of prefixing the key.
      expect(fetchSpy).not.toHaveBeenCalled();
      expect(lastStoreCall()).toEqual({
        scope: "FLOW",
        scopeKey: "flow-123",
        key: "myKey",
      });
    });
  });
});
