// Vendored from activepieces/activepieces@0.91.0 packages/core/utils/src/lib/color.ts. MIT; see ../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";

export const ColorHex = z.string().check(z.regex(/^#[0-9A-Fa-f]{6}$/));
export type ColorHex = z.infer<typeof ColorHex>;
