// Vendored from activepieces/activepieces@0.91.0 packages/core/utils/src/lib/connection-template.ts. MIT; see ../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
const CONNECTION_TEMPLATE = /^\{\{connections\['([^']+)'\]\}\}$/;

function unwrapExternalId(auth: unknown): string | null {
  if (typeof auth !== "string" || auth.length === 0) {
    return null;
  }
  return auth.match(CONNECTION_TEMPLATE)?.[1] ?? auth;
}

export const connectionTemplate = { unwrapExternalId };
