// Vendored from activepieces/activepieces@0.91.0 packages/core/utils/src/lib/form-errors.ts. MIT; see ../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
export const formErrors = {
  required: "required",
  invalidGitRepoSlug: "invalidGitRepoSlug",
  invalidGitRepoBranch: "invalidGitRepoBranch",
  invalidGitRepoRemoteUrl: "invalidGitRepoRemoteUrl",
  invalidExternalId: "invalidExternalId",
  invalidFileName: "invalidFileName",
  messageRequiresContentOrFiles: "messageRequiresContentOrFiles",
} as const;

export const SAFE_EXTERNAL_ID_PATTERN = /^(?!\.{1,2}$)[A-Za-z0-9._-]{1,128}$/;
