// Vendored from activepieces/activepieces@0.91.0 packages/core/utils/src/lib/locale.ts. MIT; see ../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
export enum LocalesEnum {
  DUTCH = "nl",
  ENGLISH = "en",
  GERMAN = "de",
  FRENCH = "fr",
  SPANISH = "es",
  JAPANESE = "ja",
  CHINESE_SIMPLIFIED = "zh",
  PORTUGUESE = "pt",
  ARABIC = "ar",
  CHINESE_TRADITIONAL = "zh-TW",
}
