// Vendored from activepieces/activepieces@0.91.0 packages/core/utils/src/lib/multipart-file.ts. MIT; see ../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";

export const ApMultipartFile = z.object({
  filename: z.string(),
  data: z.unknown(),
  type: z.literal("file"),
  mimetype: z.optional(z.string()),
});

export type ApMultipartFile = z.infer<typeof ApMultipartFile> & {
  data: Buffer;
};

export const isMultipartFile = (value: unknown): value is ApMultipartFile => {
  return (
    typeof value === "object" &&
    value !== null &&
    "type" in value &&
    value.type === "file" &&
    "filename" in value &&
    "data" in value &&
    value.data instanceof Buffer
  );
};
