// Vendored from activepieces/activepieces@0.91.0 packages/core/utils/src/lib/project-role.ts. MIT; see ../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BaseModelSchema, Nullable } from "./base-model.js";

export const ProjectRole = z.object({
  ...BaseModelSchema,
  name: z.string(),
  permissions: z.array(z.string()),
  platformId: Nullable(z.string()),
  type: z.string(),
  userCount: z.optional(z.number()),
});

export type ProjectRole = z.infer<typeof ProjectRole>;
