// Vendored from activepieces/activepieces@0.91.0 packages/core/utils/src/lib/seek-page.ts. MIT; see ../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { Nullable } from "./base-model.js";

export type Cursor = string | null;

export type SeekPage<T> = {
  next: Cursor;
  previous: Cursor;
  data: T[];
};

export const SeekPage = (t: z.ZodMiniType): z.ZodMiniType =>
  z.object({
    data: z.array(t),
    next: Nullable(z.string()),
    previous: Nullable(z.string()),
  });
