export {
  CrossBackendBatchError,
  CrossBackendRelationshipError,
  FanInPartialFailureError,
  InvalidFanInCursorError,
  isMisroute,
  messageOf,
  MisrouteUnresolvedError,
  misrouteOf,
  NoEligibleBackendError,
  NOT_MISROUTED,
  UnknownBackendError,
  WRONG_BACKEND_CODE,
  WRONG_SHARD_CODE,
  WrongBackendError,
  type MisrouteInfo,
  type WrongBackendDetails,
} from "./errors.js";
export {
  fromReactorClient,
  RouterBackend,
  UnsupportedByBackendError,
  type BackendSupports,
  type BatchSubmitter,
  type FindSupport,
  type IRoutableBackend,
  type RoutableBackendConfig,
} from "./backend.js";
export {
  collectionRequirements,
  DEFAULT_BRANCH,
  DEFAULT_DOCUMENT_CACHE_SIZE,
  DEFAULT_JOB_CACHE_SIZE,
  DEFAULT_MISROUTE_ATTEMPTS,
  DEFAULT_SUBSCRIPTION_DEDUP_SIZE,
  NO_REQUIREMENTS,
  UNKNOWN_REACTOR_INFO,
  type BackendFacts,
  type CollectionRequirements,
  type CollectionRequirementsInput,
  type ReactorReach,
  type RouteSource,
  type RouterDiagnostic,
  type RouterTableEntry,
  type RouterTableSnapshot,
  type RoutingOptions,
} from "./types.js";
export {
  eligibleBackends,
  ineligibleReason,
  placeCollection,
  placeStandalone,
} from "./placement.js";
export { RouterTable } from "./table.js";
export {
  decodeFanInCursor,
  encodeFanInCursor,
  FAN_IN_CURSOR_PREFIX,
  fanIn,
  fanInExistence,
  isFanInCursor,
  mergePaged,
  pagedParticipants,
  supportingBackends,
  type Answer,
  type BackendCursor,
  type FanInMode,
  type FanInOptions,
  type MergePagedOptions,
  type PagedParticipant,
} from "./fan-in.js";
