// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/color-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BasePropertySchema, TPropertyValue } from "./common.js";
import { PropertyType } from "./property-type.js";

export const ColorProperty = z.object({
  ...BasePropertySchema.shape,
  ...TPropertyValue(z.string(), PropertyType.COLOR).shape,
});

export type ColorProperty<R extends boolean> = BasePropertySchema &
  TPropertyValue<string, PropertyType.COLOR, R>;
