// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/date-time-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BasePropertySchema, TPropertyValue } from "./common.js";
import { PropertyType } from "./property-type.js";

export const DateTimeProperty = z.object({
  ...BasePropertySchema.shape,
  ...TPropertyValue(z.string(), PropertyType.DATE_TIME).shape,
});

export type DateTimeProperty<R extends boolean> = BasePropertySchema &
  TPropertyValue<string, PropertyType.DATE_TIME, R>;
