// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/file-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import type { Readable } from "node:stream";
import * as z from "zod/mini";
import { BasePropertySchema, TPropertyValue } from "./common.js";
import { PropertyType } from "./property-type.js";

export class ApFile {
  constructor(
    public filename: string,
    public data: Buffer,
    public extension?: string,
  ) {}

  get base64(): string {
    return this.data.toString("base64");
  }
}

export const FileProperty = z.object({
  ...BasePropertySchema.shape,
  streaming: z.optional(z.boolean()),
  ...TPropertyValue(z.unknown(), PropertyType.FILE).shape,
});

export type ApStreamingFile = {
  filename: string;
  extension?: string;
  size?: number;
  body: Readable;
};

export type FileProperty<
  R extends boolean,
  S extends boolean = false,
> = BasePropertySchema & {
  streaming?: S;
} & TPropertyValue<
    S extends true ? ApStreamingFile | ApFile : ApFile,
    PropertyType.FILE,
    R
  >;
