// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/json-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BasePropertySchema, TPropertyValue } from "./common.js";
import { PropertyType } from "./property-type.js";

export const JsonProperty = z.object({
  ...BasePropertySchema.shape,
  ...TPropertyValue(
    z.union([z.record(z.string(), z.unknown())]),
    PropertyType.JSON,
  ).shape,
});
export type JsonProperty<R extends boolean> = BasePropertySchema &
  TPropertyValue<Record<string, unknown>, PropertyType.JSON, R>;
