// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/markdown-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BasePropertySchema, TPropertyValue } from "./common.js";
import { PropertyType } from "./property-type.js";
import { MarkdownVariant } from "../../../../core-piece-types/index.js";

export const MarkDownProperty = z.object({
  ...BasePropertySchema.shape,
  ...TPropertyValue(z.void(), PropertyType.MARKDOWN).shape,
  variant: z.optional(z.enum(MarkdownVariant)),
});

export type MarkDownProperty = BasePropertySchema &
  TPropertyValue<undefined, PropertyType.MARKDOWN, false> & {
    variant?: MarkdownVariant;
  };
