// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/number-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BasePropertySchema, TPropertyValue } from "./common.js";
import { PropertyType } from "./property-type.js";

export const NumberProperty = z.object({
  ...BasePropertySchema.shape,
  display: z.optional(z.enum(["stepper"])),
  min: z.optional(z.number()),
  max: z.optional(z.number()),
  step: z.optional(z.number()),
  ...TPropertyValue(z.number(), PropertyType.NUMBER).shape,
});

export type NumberProperty<R extends boolean> = BasePropertySchema & {
  display?: "stepper";
  min?: number;
  max?: number;
  step?: number;
} & TPropertyValue<number, PropertyType.NUMBER, R>;
