// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/object-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BasePropertySchema, TPropertyValue } from "./common.js";
import { PropertyType } from "./property-type.js";

export const ObjectProperty = z.object({
  ...BasePropertySchema.shape,
  ...TPropertyValue(z.record(z.string(), z.unknown()), PropertyType.OBJECT)
    .shape,
});

export type ObjectProperty<R extends boolean> = BasePropertySchema &
  TPropertyValue<Record<string, unknown>, PropertyType.OBJECT, R>;
