// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/text-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BasePropertySchema, TPropertyValue } from "./common.js";
import { PropertyType } from "./property-type.js";

export const ShortTextProperty = z.object({
  ...BasePropertySchema.shape,
  ...TPropertyValue(z.string(), PropertyType.SHORT_TEXT).shape,
});

export type ShortTextProperty<R extends boolean> = BasePropertySchema &
  TPropertyValue<string, PropertyType.SHORT_TEXT, R>;

export const LongTextProperty = z.object({
  ...BasePropertySchema.shape,
  ...TPropertyValue(z.string(), PropertyType.LONG_TEXT).shape,
});

export type LongTextProperty<R extends boolean> = BasePropertySchema &
  TPropertyValue<string, PropertyType.LONG_TEXT, R>;
