/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import {
  type IProcessorHostModule,
  type ProcessorFactory,
  type ProcessorRecord,
} from "document-drive";
import { type PHDocumentHeader } from "document-model";

// Import other processor factories here as they are generated
import { codegenProcessorFactory } from "./codegen/factory.js";

export const processorFactory = (module: IProcessorHostModule) => {
  // Initialize all processor factories once with the module
  const factories: Array<ProcessorFactory> = [];

  // Add all processor factories

  // Add other processors here as they are generated
  factories.push(codegenProcessorFactory(module));

  // Return the inner function that will be called for each drive
  return async (driveHeader: PHDocumentHeader) => {
    const processors: ProcessorRecord[] = [];

    // Call each cached factory with the driveHeader
    for (const factory of factories) {
      processors.push(...(await factory(driveHeader)));
    }

    return processors;
  };
};
