/**
 * Generated database schema types
 * This would normally be auto-generated by `ph generate --migration-file`
 * Following the documentation pattern
 */

export interface Database {
  todo: {
    task: string;
    status: boolean;
  };
}

export type DB = Database;