await Bun.build({
  entrypoints: ["./index.ts"],
  outdir: "cdn",
  target: "browser",
  external: [
    "document-model",
    "document-drive",
    "@powerhousedao/connect",
    "@powerhousedao/design-system",
    "@powerhousedao/common",
    "@powerhousedao/config",
    "@powerhousedao/reactor-browser",
    "@powerhousedao/shared",
    "@electric-sql/pglite",
    "@electric-sql/pglite-tools",
    "@powerhousedao/builder-tools",
    "@powerhousedao/codegen",
    "@powerhousedao/ph-cli",
    "react",
    "react-dom",
    "tailwindcss",
    "@tailwindcss/cli",
    "vite",
    "vitest",
  ],
});
