// The contract lives in `@powerhousedao/shared/processors` so exactly one such type exists:
// generated processors must compile against both it and reactor-browser's host module.
export type {
  AuthorizerResult,
  IHttpScope,
  IWebhookEndpoints,
  IWebhookScope,
  NodeRouteSpec,
  RouteActor,
  RouteAuth,
  RouteAuthorizer,
  RouteBody,
  RouteContext,
  RouteHandler,
  RouteMethod,
  RouteOptions,
  RouteSpec,
  RouteTransport,
  RouteUser,
  ScopedRouteHandle,
  WebhookEndpointInfo,
  WebhookField,
  WebhookHashAlgorithm,
  WebhookPolicy,
  WebhookReply,
  WebhookRequest,
  WebhookScheme,
  WebhookSignatureEncoding,
  WebhookSpec,
  WebhookVerification,
} from "@powerhousedao/shared/processors";
