import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  academySidebar: [
    {
      type: 'category',
      label: 'Get Started',
      items: [{ type: 'autogenerated', dirName: 'academy/01-GetStarted' }],
    },
    {
      type: 'category',
      label: 'Advanced Tutorial',
      items: [{ type: 'autogenerated', dirName: 'academy/02-AdvancedTutorial' }],
    },
    {
      type: 'category',
      label: 'API References',
      items: [{ type: 'autogenerated', dirName: 'academy/03-APIReferences' }],
    },

    // Manually define the Component Library category
    {
      type: 'category',
      label: 'Component Library',
      items: [
        {
          type: 'html',
          value: `
            <a href="https://storybook.powerhouse.academy/" target="_blank" rel="noopener" style="display: flex; align-items: center; gap: 6px; font-weight: 500; text-decoration: none;">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" style="vertical-align: middle; margin-left: 13px;">
                <rect width="24" height="24" rx="4" fill="#FF4785"/>
                <text x="12" y="16" text-anchor="middle" fill="white" font-size="12" font-family="Arial" font-weight="bold">SB</text>
              </svg>
              Storybook
            </a>
          `,
        },
        // Autogenerate the rest of the docs in this folder
        {type: 'autogenerated', dirName: 'academy/04-ComponentLibrary'},
      ],
    },

    // Everything after Component Library is still autogenerated
    {
      type: 'category',
      label: 'Architecture',
      items: [{ type: 'autogenerated', dirName: 'academy/05-Architecture' }],
    },
    { type: 'doc', id: 'academy/Cookbook', label: 'Cookbook' },
    { type: 'doc', id: 'academy/Glossary', label: 'Glossary' },
    // ...add more as needed
  ],
  bookofpowerhouseSidebar: [{type: 'autogenerated', dirName: 'bookofpowerhouse'}],
};

export default sidebars;