import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * The academy sidebar is generated entirely from the filesystem under
 * docs/academy. Ordering comes from numeric folder/file prefixes (e.g. `01-`)
 * and `sidebar_position` frontmatter; category labels and links come from each
 * folder's `_category_.json`. To rearrange sections, rename the numbered
 * folders or edit their `_category_.json` — no manual sidebar entries to keep
 * in sync.
 *
 * Items that can't be expressed in the filesystem (e.g. the external Storybook
 * link) live in the navbar in docusaurus.config.ts.
 */
const sidebars: SidebarsConfig = {
  academySidebar: [{ type: "autogenerated", dirName: "academy" }],
};

export default sidebars;
