import { RealWorldAssetsState } from '..';

export const initialState: RealWorldAssetsState = {
    accounts: [
        {
            id: 'principal-lender-account-id',
            reference: '0x',
            label: 'Principal Lender',
        },
        {
            id: 'account-2',
            label: 'Account 2',
            reference: '0x456',
        },
        {
            id: 'account-3',
            label: 'Account 3',
            reference: '0x789',
        },
        {
            id: 'account-4',
            label: 'Account 4',
            reference: '0xabc',
        },
    ],
    principalLenderAccountId: 'principal-lender-account-id',
    spvs: [
        { id: '1', name: 'TACO' },
        { id: '2', name: 'SPV 2' },
        { id: '3', name: 'SPV 3' },
    ],
    serviceProviderFeeTypes: [
        {
            id: 'principal-fee-type-id',
            name: 'Principal',
            feeType: 'Principal',
            accountId: 'principal-lender-account-id',
        },
        {
            id: '1',
            feeType: 'Fee 1',
            name: 'Service Provider 1',
            accountId: 'account-2',
        },
        {
            id: '2',
            feeType: 'Fee 2',
            name: 'Service Provider 2',
            accountId: 'account-3',
        },
        {
            id: '3',
            feeType: 'Fee 3',
            name: 'Service Provider 2',
            accountId: 'account-4',
        },
    ],
    fixedIncomeTypes: [
        { id: '1', name: 'Treasury Bill' },
        { id: '2', name: 'U-Bill' },
        { id: '3', name: 'V-Bill' },
    ],
    portfolio: [
        {
            id: 'principal-asset-id',
            type: 'Cash',
            spvId: '1',
            currency: 'USD',
            balance: 500000,
        },
        {
            id: '137418',
            type: 'FixedIncome',
            fixedIncomeTypeId: '1',
            name: 'Fixed Income 1',
            spvId: '2',
            maturity: '2024-06-01T00:00:00.000Z',
            purchaseDate: '2021-03-28T00:00:00.000Z',
            notional: 0,
            purchasePrice: 0,
            purchaseProceeds: 0,
            totalDiscount: 0,
            ISIN: '771296973666',
            CUSIP: '225848609',
            coupon: 0,
            assetProceeds: 0,
            salesProceeds: 0,
            realizedSurplus: 0,
        },
        {
            id: '683189',
            type: 'FixedIncome',
            fixedIncomeTypeId: '1',
            name: 'FixedIncome 2',
            spvId: '2',
            maturity: '2024-06-15T00:00:00.000Z',
            purchaseDate: '2021-03-18T00:00:00.000Z',
            notional: 0,
            purchasePrice: 0,
            purchaseProceeds: 0,
            totalDiscount: 0,
            ISIN: '807597117063',
            CUSIP: '303442336',
            coupon: 0,
            assetProceeds: 0,
            salesProceeds: 0,
            realizedSurplus: 0,
        },
        {
            id: '752165',
            type: 'FixedIncome',
            fixedIncomeTypeId: '1',
            name: 'FixedIncome 3',
            spvId: '2',
            maturity: '2022-04-24T00:00:00.000Z',
            purchaseDate: '2022-01-03T00:00:00.000Z',
            notional: 0,
            purchasePrice: 0,
            purchaseProceeds: 0,
            totalDiscount: 0,
            ISIN: '466394625668',
            CUSIP: '319580691',
            coupon: 0,
            assetProceeds: 0,
            salesProceeds: 0,
            realizedSurplus: 0,
        },
    ],
    transactions: [
        {
            id: 'lHExR6QgOChLhp1hLpMgwp6DSb8=',
            type: 'AssetPurchase',
            entryTime: '2021-03-10T08:00:00.000Z',
            cashBalanceChange: -1,
            unitPrice: 1,
            serviceProviderFeeTypeId: null,
            txRef: '',
            fees: null,
            cashTransaction: {
                id: 'xhf50hniWmU2z2V2xuNAG0wEc3Q=',
                assetType: 'Cash',
                assetId: 'principal-asset-id',
                entryTime: '2021-03-10T08:00:00.000Z',
                counterPartyAccountId: 'principal-lender-account-id',
                amount: 1,
                accountId: null,
                settlementTime: null,
                tradeTime: null,
            },
            fixedIncomeTransaction: {
                id: 'pdye3pGkpgu6xd2jlavUvYNO3ws=',
                assetType: 'FixedIncome',
                assetId: '137418',
                amount: 1,
                entryTime: '2021-03-10T08:00:00.000Z',
                accountId: null,
                counterPartyAccountId: null,
                settlementTime: null,
                tradeTime: null,
            },
        },
        {
            id: 'HTrhJ48zryWnNZvSSWKiDrY2xpk=',
            type: 'AssetPurchase',
            entryTime: '2021-03-10T08:00:00.000Z',
            cashBalanceChange: -1,
            unitPrice: 1,
            serviceProviderFeeTypeId: null,
            txRef: '',
            fees: null,
            cashTransaction: {
                id: 'VsVpcjgnHEjrtRQr6wFmj8p7QLY=',
                assetType: 'Cash',
                assetId: 'principal-asset-id',
                entryTime: '2021-03-10T08:00:00.000Z',
                counterPartyAccountId: 'principal-lender-account-id',
                amount: 1,
                accountId: null,
                settlementTime: null,
                tradeTime: null,
            },
            fixedIncomeTransaction: {
                id: 'obNt3tekVIbUe4sI/4VTvdErTyg=',
                assetType: 'FixedIncome',
                assetId: '137418',
                amount: 1,
                entryTime: '2021-03-10T08:00:00.000Z',
                accountId: null,
                counterPartyAccountId: null,
                settlementTime: null,
                tradeTime: null,
            },
        },
        {
            id: 'o5HN+5wCQ9oe/sTu6wbM5Z6cDDA=',
            type: 'AssetPurchase',
            entryTime: '2021-03-10T08:00:00.000Z',
            cashBalanceChange: -1,
            unitPrice: 1,
            serviceProviderFeeTypeId: null,
            txRef: '',
            fees: null,
            cashTransaction: {
                id: 'EkeVhlh2Jfq1FvpRZF0z7UAB1zo=',
                assetType: 'Cash',
                assetId: 'principal-asset-id',
                entryTime: '2021-03-10T08:00:00.000Z',
                counterPartyAccountId: 'principal-lender-account-id',
                amount: 1,
                accountId: null,
                settlementTime: null,
                tradeTime: null,
            },
            fixedIncomeTransaction: {
                id: 'XM7mv94ybT8CLdhdzu1QpMWzd/I=',
                assetType: 'FixedIncome',
                assetId: '137418',
                amount: 1,
                entryTime: '2021-03-10T08:00:00.000Z',
                accountId: null,
                counterPartyAccountId: null,
                settlementTime: null,
                tradeTime: null,
            },
        },
    ],
};
