// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/authentication/basic-auth-prop.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { TPropertyValue } from "../input/common.js";
import { PropertyType } from "../input/property-type.js";
import { BasePieceAuthSchema } from "./common.js";

export const BasicAuthPropertyValue = z.object({
  username: z.string(),
  password: z.string(),
});

export type BasicAuthPropertyValue = z.infer<typeof BasicAuthPropertyValue>;

export const BasicAuthProperty = z.object({
  ...BasePieceAuthSchema.shape,
  username: z.object({
    displayName: z.string(),
    description: z.optional(z.string()),
  }),
  password: z.object({
    displayName: z.string(),
    description: z.optional(z.string()),
  }),
  ...TPropertyValue(BasicAuthPropertyValue, PropertyType.BASIC_AUTH).shape,
});

export type BasicAuthProperty = BasePieceAuthSchema<BasicAuthPropertyValue> & {
  username: {
    displayName: string;
    description?: string;
  };
  password: {
    displayName: string;
    description?: string;
  };
} & TPropertyValue<BasicAuthPropertyValue, PropertyType.BASIC_AUTH, true>;
