// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/authentication/common.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import type {
  AuthValidationServerContext,
  ServerContext,
} from "../../context/index.js";

export const BasePieceAuthSchema = z.object({
  displayName: z.string(),
  description: z.optional(z.string()),
  hasConnectionIdentifier: z.optional(z.boolean()),
});

export type BasePieceAuthSchema<AuthValueSchema> = {
  displayName: string;
  description?: string;
  validate?: (params: {
    auth: AuthValueSchema;
    server: AuthValidationServerContext;
  }) => Promise<
    | { valid: true }
    | {
        valid: false;
        error: string;
      }
  >;
  // Resolves a human-readable label for a connection made with this auth
  // (e.g. the account email, or Slack's "display-name (workspace)"), shown in
  // the UI so users can tell which account a connection belongs to. Best-effort.
  getConnectionIdentifier?: (params: {
    auth: AuthValueSchema;
    server: Omit<ServerContext, "token">;
  }) => Promise<string | undefined>;
  // Derived by Piece.metadata(), not authored: functions cannot survive metadata
  // serialization, so the server has no other way to tell whether the hook above
  // exists before paying for an engine round-trip.
  hasConnectionIdentifier?: boolean;
};
