// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/authentication/secret-text-property.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";
import { BasePieceAuthSchema } from "./common.js";
import { TPropertyValue } from "../input/common.js";
import { PropertyType } from "../input/property-type.js";

export const SecretTextProperty = z.object({
  ...BasePieceAuthSchema.shape,
  ...TPropertyValue(
    z.object({
      auth: z.string(),
    }),
    PropertyType.SECRET_TEXT,
  ).shape,
});

export type SecretTextProperty<R extends boolean> =
  BasePieceAuthSchema<string> &
    TPropertyValue<string, PropertyType.SECRET_TEXT, R>;
