---
to: "<%= rootDir %>/factory.ts"
unless_exists: true
---
/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import { type ProcessorRecord, type IProcessorHostModule, type ProcessorFactory } from "document-drive";
import { type PHDocumentHeader } from "document-model";

// Import other processor factories here as they are generated

export const processorFactory = (module: IProcessorHostModule) => {
  // Initialize all processor factories once with the module
  const factories: Array<ProcessorFactory> = [];
  
  // Add all processor factories
  
  // Add other processors here as they are generated
  
  // Return the inner function that will be called for each drive
  return async (driveHeader: PHDocumentHeader): Promise<ProcessorRecord[]> => {
    const processors: ProcessorRecord[] = [];
    
    // Call each cached factory with the driveHeader
    for (const factory of factories) {
      const factoryProcessors = await factory(driveHeader);
      processors.push(...factoryProcessors);
    }
    
    return processors;
  };
}

