// Hardcoded so ph-cmd's dispatch doesn't have to evaluate phCliHelpCommands.
// The compile-time guard in args/help.ts catches drift.
export const phCliCommandNames = [
  "generate",
  "vetra",
  "connect",
  "build",
  "code",
  "publish",
  "list",
  "l",
  "access-token",
  "registry-login",
  "inspect",
  "is",
  "migrate",
  "switchboard",
  "reactor",
  "login",
  "logout",
  "install",
  "add",
  "i",
  "uninstall",
  "remove",
] as const;
