/**
* TODO: move scaffold file to autogenerated ../gen/. There shouldn't be any manual code left. 
*/

import { DocumentModelState } from "@acaldas/document-model-graphql/document-model";
import { ExtendedDocumentModelState, DocumentModelAction } from "../gen";
import { reducer } from '..';
import { 
    FileInput,
    loadFromFile,
    loadFromInput,
    saveToFile,
    saveToFileHandle, 
} from '../../document/utils';

export const createEmptyDocumentModelState = (): DocumentModelState => ({
    "id": "",
    "name": "",
    "extension": "",
    "description": "",
    "author": {
        "name": "",
        "website": ""
    },
    "specifications": [
        {
            "version": 1,
            "changeLog": [],
            "state": {
                "schema": "",
                "initialValue": "",
                "examples": []
            },
            "modules": []
        }
    ]
});

const dateTimeNow = (new Date()).toISOString();
export const createEmptyExtendedDocumentModelState = (): ExtendedDocumentModelState => ({
    // Component 1: document header
    name: "",
    created: dateTimeNow,
    lastModified: dateTimeNow,
    documentType: "powerhouse/document-model",
    revision: 0,

    // Component 2: (strict) state object
    state: createEmptyDocumentModelState(),

    // Component 3: file registry
    fileRegistry: {},

    // TODO: remove operations, lift to the document level structure: operations = { fileRegistry:File[], history:Operation[] }
    operations: [],

    // TODO: remove initialState, lift to the document level (with type: ExtendedDocumentModelState)
    initialState: {
        name: "",
        created: dateTimeNow,
        lastModified: dateTimeNow,
        documentType: "powerhouse/document-model",
        revision: 0,
        state: createEmptyDocumentModelState(),
        fileRegistry: {},
        operations: []
    }
});

export const loadDocumentModelFromFile = async (path: string) => {
    return loadFromFile<DocumentModelState, DocumentModelAction>(
        path,
        reducer
    );
};

export const loadDocumentModelFromInput = async (
    input: FileInput
): Promise<ExtendedDocumentModelState> => {
    return loadFromInput<DocumentModelState, DocumentModelAction>(
        input,
        reducer
    );
};

export const saveDocumentModelToFile = (
    document: ExtendedDocumentModelState,
    path: string,
    name?: string
): Promise<string> => {
    return saveToFile(document, path, 'phdm', name);
};

export const saveDocumentModelToFileHandle = async (
    document: ExtendedDocumentModelState,
    input: FileSystemFileHandle
) => {
    return saveToFileHandle(document, input);
};