// Vendored from activepieces/activepieces@0.91.0 packages/server/engine/test/variables/props-resolver.test.ts. MIT; see ../../../../../pieces-framework/LICENSE.
// Generated by packages/pieces-framework/scripts/sync-upstream.mts — do not edit by hand.
import {
  ApFile,
  LATEST_CONTEXT_VERSION,
  PieceAuth,
  Property,
} from "@powerhousedao/pieces-framework";
import type { PropertySettings } from "../../../upstream-adapters/shared.js";
import { PropertyExecutionType } from "../../../upstream-adapters/shared.js";
import { propsProcessor } from "../../../upstream-adapters/props-processor.js";
describe("Props resolver", () => {
  // Deliberate divergence: our FILE handling: a data URI becomes a plain object named file.<ext>, not an ApFile
  it.fails("should return base64 from base64 with mime only", async () => {
    const input = {
      base64WithMime:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAiAAAAC4CAYAAADaI1cbAAA0h0lEQVR4AezdA5AlPx7A8Zxt27Z9r5PB2SidWTqbr26S9Hr/tm3btu3723eDJD3r15ec17vzXr+Z",
      base64:
        "iVBORw0KGgoAAAANSUhEUgAAAiAAAAC4CAYAAADaI1cbAAA0h0lEQVR4AezdA5AlPx7A8Zxt27Z9r5PB2SidWTqbr26S9Hr/tm3btu3723eDJD3r15ec17vzXr+Z",
    };
    const props = {
      base64WithMime: Property.File({
        displayName: "Base64",
        required: true,
      }),
      base64: Property.File({
        displayName: "Base64",
        required: true,
      }),
    };
    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );
    expect(processedInput).toEqual({
      base64: null,
      base64WithMime: new ApFile(
        "unknown.png",
        Buffer.from(
          "iVBORw0KGgoAAAANSUhEUgAAAiAAAAC4CAYAAADaI1cbAAA0h0lEQVR4AezdA5AlPx7A8Zxt27Z9r5PB2SidWTqbr26S9Hr/tm3btu3723eDJD3r15ec17vzXr+Z",
          "base64",
        ),
        "png",
      ),
    });
    expect(errors).toEqual({
      base64: [
        "Expected file url or base64 with mimeType, received: iVBORw0KGgoAAAANSUhEUgAAAiAAAAC4CAYAAADaI1cbAAA0h0lEQVR4AezdA5AlPx7A8Zxt27Z9r5PB2SidWTqbr26S9Hr/tm3btu3723eDJD3r15ec17vzXr+Z",
      ],
    });
  });

  // Not applicable here: fetches cdn.activepieces.com
  it.skip("should resolve files inside the array properties", async () => {
    const input = {
      documents: [
        {
          file: "https://cdn.activepieces.com/brand/logo.svg?token=123",
        },
      ],
    };
    const props = {
      documents: Property.Array({
        displayName: "Documents",
        required: true,
        properties: {
          file: Property.File({
            displayName: "File",
            required: true,
          }),
        },
      }),
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );
    expect(processedInput.documents[0].file).toBeDefined();
    expect(processedInput.documents[0].file.extension).toBe("svg");
    expect(processedInput.documents[0].file.filename).toBe("logo.svg");
    expect(errors).toEqual({});
  });

  it("should return error for invalid file inside the array properties", async () => {
    const input = {
      documents: [
        {
          file: "invalid-url",
        },
      ],
    };
    const props = {
      documents: Property.Array({
        displayName: "Documents",
        required: true,
        properties: {
          file: Property.File({
            displayName: "File",
            required: true,
          }),
        },
      }),
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );
    expect(processedInput.documents[0].file).toBeNull();
    expect(errors).toEqual({
      documents: {
        properties: [
          {
            file: [
              "Expected file url or base64 with mimeType, received: invalid-url",
            ],
          },
        ],
      },
    });
  });
  // Not applicable here: fetches cdn.activepieces.com
  it.skip("should return images for image url", async () => {
    const input = {
      file: "https://cdn.activepieces.com/brand/logo.svg?token=123",
    };
    const props = {
      file: Property.File({
        displayName: "File",
        required: true,
      }),
    };
    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );
    expect(processedInput.file).toBeDefined();
    expect(processedInput.file.extension).toBe("svg");
    expect(processedInput.file.filename).toBe("logo.svg");
    expect(errors).toEqual({});
  });

  // Test with invalid url
  // Not applicable here: fetches google.com
  it.skip("should return error for invalid data", async () => {
    const input = {
      file: "https://google.com",
      nullFile: null,
      nullOptionalFile: null,
    };
    const props = {
      file: Property.File({
        displayName: "File",
        required: true,
      }),
      nullFile: Property.File({
        displayName: "File",
        required: true,
      }),
      nullOptionalFile: Property.File({
        displayName: "File",
        required: false,
      }),
    };
    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );

    expect(processedInput.file).toBeDefined();
    expect(processedInput.file.extension).toBe("html");
    expect(processedInput.file.filename).toBe("unknown.html");
    expect(processedInput.nullFile).toBeNull();
    expect(processedInput.nullOptionalFile).toBeNull();

    expect(errors).toEqual({
      nullFile: ["Expected file url or base64 with mimeType, received: null"],
    });
  });

  // Known divergence (README: CUSTOM_AUTH props are not coerced): a CUSTOM_AUTH value reaches the piece without its props coerced
  it.fails("should return casted number for text", async () => {
    const input = {
      price: "0",
      auth: {
        age: "12",
      },
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        {
          price: Property.Number({
            displayName: "Price",
            required: true,
          }),
        },
        PieceAuth.CustomAuth({
          required: true,
          props: {
            age: Property.Number({
              displayName: "age",
              required: true,
            }),
          },
        }),
        true,
        {},
      );

    expect(processedInput).toEqual({
      auth: {
        age: 12,
      },
      price: 0,
    });
    expect(errors).toEqual({});
  });

  it("should not error if auth configured, but no auth provided in input", async () => {
    const input = {
      price: "0",
    };
    const props = {
      price: Property.Number({
        displayName: "Price",
        required: true,
      }),
    };
    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.CustomAuth({
          required: true,
          props: {},
        }),
        false,
        {},
      );

    expect(processedInput).toEqual({
      price: 0,
    });
    expect(errors).toEqual({});
  });

  // Known divergence (README: DYNAMIC values are not re-processed): a DYNAMIC value is not re-processed against the schema it resolved to
  it.fails("should flatten arrays inside DYNAMIC properties", async () => {
    const input = {
      dynamicProp: {
        items: {
          id: [1, 2],
          name: ["Item 1", "Item 2"],
        },
      },
    };
    const propertySettings: Record<string, PropertySettings> = {
      dynamicProp: {
        type: PropertyExecutionType.MANUAL,
        schema: {
          items: Property.Array({
            displayName: "Items",
            required: true,
            properties: {
              id: Property.Number({
                displayName: "ID",
                required: true,
              }),
              name: Property.LongText({
                displayName: "Name",
                required: true,
              }),
            },
          }),
        },
      },
    };
    const props = {
      dynamicProp: Property.DynamicProperties({
        auth: undefined,
        displayName: "Dynamic Property",
        required: true,
        props: async () => {
          return {};
        },
        refreshers: [],
      }),
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        propertySettings,
      );

    expect(processedInput.dynamicProp.items).toEqual([
      { id: 1, name: "Item 1" },
      { id: 2, name: "Item 2" },
    ]);
    expect(errors).toEqual({});
  });
});

describe("Array Flatter Processor", () => {
  it("should flatten array of objects", async () => {
    const input = {
      items: {
        id: [1, 2],
        name: ["Item 1", "Item 2"],
      },
    };
    const props = {
      items: Property.Array({
        displayName: "Items",
        required: true,
        properties: {
          id: Property.Number({
            displayName: "ID",
            required: true,
          }),
          name: Property.LongText({
            displayName: "Name",
            required: true,
          }),
        },
      }),
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );

    expect(processedInput.items).toEqual([
      { id: 1, name: "Item 1" },
      { id: 2, name: "Item 2" },
    ]);
    expect(errors).toEqual({});
  });

  it("should handle non-array properties gracefully", async () => {
    const input = {
      items: {
        id: [1, 2],
        name: "Single Item", // Non-array property
      },
    };
    const props = {
      items: Property.Array({
        displayName: "Items",
        required: true,
        properties: {
          id: Property.Number({
            displayName: "ID",
            required: true,
          }),
          name: Property.LongText({
            displayName: "Name",
            required: true,
          }),
        },
      }),
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );

    expect(processedInput.items).toEqual([
      { id: 1, name: "Single Item" },
      { id: 2, name: "Single Item" },
    ]);
    expect(errors).toEqual({});
  });

  it("should handle arrays of unequal length", async () => {
    const input = {
      items: {
        id: [1, 2, 3], // Longer array
        name: ["Item 1", "Item 2"], // Shorter array
      },
    };
    const props = {
      items: Property.Array({
        displayName: "Items",
        required: true,
        properties: {
          id: Property.Number({
            displayName: "ID",
            required: true,
          }),
          name: Property.LongText({
            displayName: "Name",
            required: false,
          }),
        },
      }),
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );

    expect(processedInput.items).toEqual([
      { id: 1, name: "Item 1" },
      { id: 2, name: "Item 2" },
      { id: 3, name: undefined }, // Handle missing name
    ]);
    expect(errors).toEqual({});
  });

  it("should convert number to string for ShortText properties", async () => {
    const input = {
      items: {
        id: 123,
        name: "Item Name",
      },
    };
    const props = {
      items: Property.Array({
        displayName: "Items",
        required: true,
        properties: {
          id: Property.ShortText({
            displayName: "ID",
            required: true,
          }),
          name: Property.LongText({
            displayName: "Name",
            required: true,
          }),
        },
      }),
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );

    expect(processedInput.items).toEqual([{ id: "123", name: "Item Name" }]);
    expect(errors).toEqual({});
  });

  it("should handle arrays with string values", async () => {
    const input = {
      items: {
        id: "1",
        name: "item1",
      },
    };
    const props = {
      items: Property.Array({
        displayName: "Items",
        required: true,
        properties: {
          id: Property.ShortText({
            displayName: "ID",
            required: true,
          }),
          name: Property.LongText({
            displayName: "Name",
            required: true,
          }),
        },
      }),
    };

    const { processedInput, errors } =
      await propsProcessor.applyProcessorsAndValidators(
        input,
        props,
        PieceAuth.None(),
        false,
        {},
      );

    expect(processedInput.items).toEqual([{ id: "1", name: "item1" }]);
    expect(errors).toEqual({});
  });
});
