// Generated by test/definition/regenerate-scalar-inventory.ts. Do not edit.
//
// The catalog's published metadata, as committed bytes. A module rather
// than a .json file so both the Node suite here and the browser suite in
// reactor-browser can import it without a loader or a file read.
import type { ScalarInventory } from "../scalar-inventory.js";

export const SCALAR_CATALOG_INVENTORY: ScalarInventory = {
  kind: "powerhouse.scalar-catalog",
  formatVersion: 1,
  catalogDigest:
    "sha256:7dcee9e11d593490060661c509c6105a09b5632b561e6e663d2194867ab28799",
  validationProfiles: ["document-engineering-1.40"],
  names: [
    "PHID",
    "OID",
    "OLabel",
    "Currency",
    "EmailAddress",
    "EthereumAddress",
    "URL",
    "Date",
    "DateTime",
    "Amount_Money",
    "Amount_Percentage",
    "Amount_Tokens",
    "Amount",
    "Amount_Fiat",
    "Amount_Crypto",
    "Amount_Currency",
    "Upload",
    "Address",
    "AttachmentRef",
    "Unknown",
    "JSONObject",
  ],
  entries: [
    {
      name: "PHID",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:e265441eeac3ab270c9aa83b7a012532ba1459def233233c1f8e9a6b15d1a0ec",
      coercionSource: "derived",
    },
    {
      name: "OID",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:ecd1d41e95b238e642fc28c36d5be495b654917355123708f5a4d7dd2f8b215f",
      coercionSource: "derived",
    },
    {
      name: "OLabel",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:0bfed057a4fa9604e3327e6682f6e17b19143353acae0e2750b3d691d265508b",
      coercionSource: "derived",
    },
    {
      name: "Currency",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:6ab0f057259001789912b60e275073381e3b4b15a7b71a978f865b4de1ee241f",
      coercionSource: "derived",
    },
    {
      name: "EmailAddress",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:3d7fe597d03e59bc19259216c84f757951a52302339e9fd9fe2127de3b1019e1",
      coercionSource: "derived",
    },
    {
      name: "EthereumAddress",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:6eab8fc9a4c032c663c21647b4fc6874b171c308a8a5156b333f1430b7bb48bd",
      coercionSource: "derived",
    },
    {
      name: "URL",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:b9a83a4e0565ad026989807c1137f5a4bcf77730c654927e7256ea96aa0ff55e",
      coercionSource: "derived",
    },
    {
      name: "Date",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:c841ea62c423e59b96e6a1863ab45f111c7e57fa95cc0d47c4f1ca37547bb40a",
      coercionSource: "derived",
    },
    {
      name: "DateTime",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:5155de8660092eb66d5d52197903678bb709ce248719c36e0d394df2ccf98217",
      coercionSource: "derived",
    },
    {
      name: "Amount_Money",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:e7e108f5b7731d735175d47456272d9f8e504607c88538a3aab4d174b11d7248",
      coercionSource: "explicit",
    },
    {
      name: "Amount_Percentage",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:735c7c7256431278eb852933324fa0a1b51dbd30803579decab16ebe574d5bf5",
      coercionSource: "explicit",
    },
    {
      name: "Amount_Tokens",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:f8d31cb4931bed157f59af963e35899671c1c8453cd66b4987c65a635a304069",
      coercionSource: "explicit",
    },
    {
      name: "Amount",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:1973b1d451709d7e92c2cab73eb19ca410cd7d76237529adddef419bf977f5a8",
      coercionSource: "explicit",
    },
    {
      name: "Amount_Fiat",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:4826a0e85e056bf1779f9fbe3f0bb34124b7c053847ea4a766ddd1332a41a05a",
      coercionSource: "explicit",
    },
    {
      name: "Amount_Crypto",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:4c1c921cb43aefdf27738e09921e6bbf45d1b49184684f0b77eb1a4d9a2c08ce",
      coercionSource: "explicit",
    },
    {
      name: "Amount_Currency",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:a2af6f18dd02aa1774c978adc5fc0606f4124eb4d87010475e27455bc9032dec",
      coercionSource: "explicit",
    },
    {
      name: "Upload",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:9d164168f7af170ed0195b3fc556fbfdc7b0573fef59f4096220b332fc619dd3",
      coercionSource: "explicit",
    },
    {
      name: "Address",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:cf747ba3b37670885405681f7549788f33b0b5e9c1fa0fc2b0d7f325434562c7",
      coercionSource: "derived",
    },
    {
      name: "AttachmentRef",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:79b107722ac9cdb53b91b30d620ac80f2a0880baae9609364f0d1f94c50bbf75",
      coercionSource: "derived",
    },
    {
      name: "Unknown",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:3c13383a59169507fe9fa76c317239ea58d9efcf0656f50a1e0f966e6e465a19",
      coercionSource: "explicit",
    },
    {
      name: "JSONObject",
      validationProfile: "document-engineering-1.40",
      definitionDigest:
        "sha256:f49b6dac5285b98a63f77d1d7b1832d7ea797cf571bb96972d8d8f5672d6d4ce",
      coercionSource: "derived",
    },
  ],
  diagnostics: [],
} as const;
