name: End-to-end tests

on:
  pull_request:
    branches:
      - main
      - develop
      - staging
      - production
      - deployments/**
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
          start: npm run dev:web
          wait-on: 'http://localhost:5173/'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PH_CONNECT_ROUTER_BASENAME: /
          PH_CONNECT_DEFAULT_DRIVES_URL: