name: Release

on:
    push:
        branches: [main, staging, develop]
    workflow_dispatch:

env:
    HUSKY: 0

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 20.x
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_and_publish:
    needs: [release]
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref:  ${{ github.ref_name }}
    - uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - name: install dependencies
      run: yarn --frozen-lockfile
    - name: build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish