// Vendored from activepieces/activepieces@0.91.0 packages/pieces/framework/src/lib/property/input/dropdown/common.ts. MIT; see ../../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import * as z from "zod/mini";

export const DropdownOption = z.object({
  label: z.string(),
  value: z.unknown(),
  description: z.optional(z.string()),
  icon: z.optional(z.string()),
});

export type DropdownOption<T> = {
  label: string;
  value: T;
  description?: string;
  icon?: string;
};

export const DropdownState = z.object({
  disabled: z.optional(z.boolean()),
  placeholder: z.optional(z.string()),
  options: z.array(DropdownOption),
});

export type DropdownState<T> = {
  disabled?: boolean;
  placeholder?: string;
  options: DropdownOption<T>[];
};
