// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/base-http-client.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import type { Authentication } from "../../authentication/index.js";
import type { DelegatingAuthenticationConverter } from "./delegating-authentication-converter.js";
import type { HttpClient } from "./http-client.js";
import { HttpHeader } from "./http-header.js";
import type { HttpHeaders } from "./http-headers.js";
import type { HttpMessageBody } from "./http-message-body.js";
import type { HttpRequest } from "./http-request.js";
import type { HttpRequestBody } from "./http-request-body.js";
import type { HttpResponse } from "./http-response.js";
import { MediaType } from "./media-type.js";

export abstract class BaseHttpClient implements HttpClient {
  constructor(
    private readonly baseUrl: string,
    private readonly authenticationConverter: DelegatingAuthenticationConverter,
  ) {}

  abstract sendRequest<
    RequestBody extends HttpMessageBody,
    ResponseBody extends HttpMessageBody,
  >(request: HttpRequest<RequestBody>): Promise<HttpResponse<ResponseBody>>;

  protected getUrl<RequestBody extends HttpMessageBody>(
    request: HttpRequest<RequestBody>,
  ): {
    urlWithoutQueryParams: string;
    queryParams: URLSearchParams;
  } {
    const url = new URL(`${this.baseUrl}${request.url}`);
    const urlWithoutQueryParams = `${url.origin}${url.pathname}`;
    const queryParams = new URLSearchParams();
    // Extract query parameters
    url.searchParams.forEach((value, key) => {
      queryParams.append(key, value);
    });
    return {
      urlWithoutQueryParams,
      queryParams,
    };
  }

  protected getHeaders<RequestBody extends HttpRequestBody>(
    request: HttpRequest<RequestBody>,
  ): HttpHeaders {
    let requestHeaders: HttpHeaders = {
      [HttpHeader.ACCEPT]: MediaType.APPLICATION_JSON,
    };

    if (request.authentication) {
      this.populateAuthentication(request.authentication, requestHeaders);
    }

    if (request.body) {
      switch (request.headers?.["Content-Type"]) {
        case "text/csv":
          requestHeaders[HttpHeader.CONTENT_TYPE] = MediaType.TEXT_CSV;
          break;

        default:
          requestHeaders[HttpHeader.CONTENT_TYPE] = MediaType.APPLICATION_JSON;
          break;
      }
    }
    if (request.headers) {
      requestHeaders = { ...requestHeaders, ...request.headers };
    }
    return requestHeaders;
  }

  private populateAuthentication(
    authentication: Authentication,
    headers: HttpHeaders,
  ): void {
    this.authenticationConverter.convert(authentication, headers);
  }
}
