// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/delegating-authentication-converter.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import type { HttpHeaders } from "./http-headers.js";
import { HttpHeader } from "./http-header.js";
import type {
  Authentication,
  BasicAuthentication,
  BearerTokenAuthentication,
} from "../../authentication/index.js";
import { AuthenticationType } from "../../authentication/index.js";

export class DelegatingAuthenticationConverter implements AuthenticationConverter<Authentication> {
  private readonly converters: Record<
    AuthenticationType,
    AuthenticationConverter<any>
  >;

  constructor(
    bearerTokenConverter = new BearerTokenAuthenticationConverter(),
    basicTokenConverter = new BasicTokenAuthenticationConverter(),
  ) {
    this.converters = {
      [AuthenticationType.BEARER_TOKEN]: bearerTokenConverter,
      [AuthenticationType.BASIC]: basicTokenConverter,
    };
  }

  convert(authentication: Authentication, headers: HttpHeaders): HttpHeaders {
    const converter = this.converters[authentication.type];
    return converter.convert(authentication, headers);
  }
}

class BearerTokenAuthenticationConverter implements AuthenticationConverter<BearerTokenAuthentication> {
  convert(
    authentication: BearerTokenAuthentication,
    headers: HttpHeaders,
  ): HttpHeaders {
    headers[HttpHeader.AUTHORIZATION] = `Bearer ${authentication.token}`;
    return headers;
  }
}

class BasicTokenAuthenticationConverter implements AuthenticationConverter<BasicAuthentication> {
  convert(
    authentication: BasicAuthentication,
    headers: HttpHeaders,
  ): HttpHeaders {
    const credentials = `${authentication.username}:${authentication.password}`;
    const encoded = Buffer.from(credentials).toString("base64");
    headers[HttpHeader.AUTHORIZATION] = `Basic ${encoded}`;
    return headers;
  }
}

type AuthenticationConverter<T extends Authentication> = {
  convert: (authentication: T, headers: HttpHeaders) => HttpHeaders;
};
