// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/http-client.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import type { SendRequestOptions } from "./fetch-http-client.js";
import { FetchHttpClient } from "./fetch-http-client.js";
import type { HttpMessageBody } from "./http-message-body.js";
import type { HttpRequest } from "./http-request.js";
import type { HttpRequestBody } from "./http-request-body.js";
import type { HttpResponse } from "./http-response.js";

export type HttpClient = {
  sendRequest<
    RequestBody extends HttpRequestBody,
    ResponseBody extends HttpMessageBody,
  >(
    request: HttpRequest<RequestBody>,
    options?: SendRequestOptions,
  ): Promise<HttpResponse<ResponseBody>>;
};

export const httpClient = new FetchHttpClient();
