// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/http-response.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import type { HttpMessageBody } from "./http-message-body.js";
import type { HttpHeaders } from "./http-headers.js";

export type HttpResponse<RequestBody extends HttpMessageBody = any> = {
  status: number;
  headers?: HttpHeaders | undefined;
  body: RequestBody;
};
