// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/http-headers.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
export type HttpHeaders = Record<string, string | string[] | undefined>;
