// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/http-header.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
export enum HttpHeader {
  AUTHORIZATION = "Authorization",
  ACCEPT = "Accept",
  API_KEY = "x-api-key",
  CONTENT_TYPE = "Content-Type",
}
