// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/http-request.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import type { HttpMethod } from "./http-method.js";
import type { QueryParams } from "./query-params.js";
import type { HttpHeaders } from "./http-headers.js";
import type { Authentication } from "../../authentication/index.js";
import type { HttpRequestBody } from "./http-request-body.js";

export type HttpRequest<RequestBody extends HttpRequestBody = any> = {
  method: HttpMethod;
  url: string;
  body?: RequestBody | undefined;
  headers?: HttpHeaders;
  authentication?: Authentication | undefined;
  queryParams?: QueryParams | undefined;
  timeout?: number;
  retries?: number;
  responseType?: "arraybuffer" | "json" | "blob" | "text" | "stream";
  followRedirects?: boolean;
};
