// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/http-request-body.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
import type { HttpMessageBody } from "./http-message-body.js";

export type HttpRequestBody = HttpMessageBody | string;
