// Vendored from activepieces/activepieces@0.91.0 packages/pieces/common/src/lib/http/core/media-type.ts. MIT; see ../../../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
export enum MediaType {
  APPLICATION_JSON = "application/json",
  TEXT_CSV = "text/csv",
}
