await Bun.build({
  entrypoints: [
    "./src/main.tsx",
    "./src/connect.config.ts",
    "./src/components/index.ts",
    "./src/services/index.ts",
    "./src/connect.config.ts",
    "./src/context/index.ts",
    "./src/hooks/index.ts",
    "./src/i18n/index.ts",
    "./src/pages/index.ts",
    "./src/services/index.ts",
    "./src/store/index.ts",
    "./src/utils/index.ts",
  ],
  outdir: "dist",
  target: "browser",
  root: ".",
  external: [
    "react",
    "react-dom",
    "@electric-sql/pglite",
    "@electric-sql/pglite-tools",
    "@powerhousedao/design-system",
    "@powerhousedao/builder-tools",
    "@powerhousedao/common",
    "@powerhousedao/config",
    "document-model",
    "document-drive",
    "vite",
  ],
});
