/// <reference types="vite/client" />

import type { ConnectRuntimeEnv } from "@powerhousedao/builder-tools";
import type { IPackageManager } from "@powerhousedao/reactor-browser";

declare module "virtual:ph-bundled-packages" {
  /**
   * Registers every package marked as provider: "local" in
   * powerhouse.config.json with the package manager. Generated by
   * `phBundledPackagesPlugin` at build time. No-op when no local packages
   * are declared.
   */
  const registerBundledPackages: (packageManager: IPackageManager) => void;
  export default registerBundledPackages;
}

interface ViteTypeOptions {
  // By adding this line, you can make the type of ImportMetaEnv strict
  // to disallow unknown keys.
  strictImportMetaEnv: unknown;
}

declare global {
  interface ImportMetaEnv extends ConnectRuntimeEnv {
    readonly VITE_APP_TITLE: string;
    // more env variables...
  }
}
interface ImportMeta {
  readonly env: ConnectRuntimeEnv;
}
