// export * from "./access-token.old.js";
export * from "./access-token.js";
// export * from "./connect.old.js";
export * from "./connect.js";
// export * from "./generate.old.js";
export * from "./generate.js";
// export * from "./inspect.old.js";
export * from "./inspect.js";
// export * from "./install.old.js";
export * from "./install.js";
// export * from "./list.old.js";
export * from "./list.js";
// export * from "./login.old.js";
export * from "./login.js";
// export * from "./migrate.old.js";
export * from "./migrate.js";
// export * from "./service.old.js";
export * from "./service.js";
// export * from "./switchboard.old.js";
export * from "./switchboard.js";
// export * from "./uninstall.old.js";
export * from "./uninstall.js";
// export * from "./help.old.js";
export * from "./help.js";
// export * from "./vetra.old.js";
export * from "./vetra.js";
