export {
  AttachmentAlreadyExists,
  AttachmentNotFound,
  AttachmentPending,
  AttachmentTransferError,
  HashMismatch,
  InvalidAttachmentMetadata,
  InvalidAttachmentRef,
  ReservationNotFound,
  SizeMismatch,
  UploadTooLarge,
  AttachmentService,
  KyselyAttachmentStore,
  KyselyReservationStore,
  DEFAULT_RESERVATION_TTL_MS,
  runAttachmentMigrations,
  ATTACHMENT_SCHEMA,
  parseRef,
  createRef,
  DirectAttachmentUpload,
  DirectAttachmentUploadFactory,
  FilesystemAttachmentBackend,
  parseAttachmentDownloadTarget,
  parseAttachmentUploadTarget,
  SwitchboardAttachmentTransport,
  RemoteReservationStore,
  RemoteAttachmentUpload,
  RemoteAttachmentUploadFactory,
  RemoteAttachmentStore,
  createRemoteAttachmentService,
  createFetchUploadTransport,
  createXhrUploadTransport,
  NullAttachmentTransport,
  AttachmentBuilder,
  AttachmentSchemaCompiler,
  AttachmentReferenceIndexBuilder,
  AttachmentReferenceReadModel,
  KyselyAttachmentReferenceStore,
  ATTACHMENT_REFERENCE_SCHEMA,
  ATTACHMENT_REFERENCE_READ_MODEL_ID,
  ATTACHMENT_REFERENCE_MIGRATION_TABLE,
  ATTACHMENT_REFERENCE_MIGRATION_LOCK_TABLE,
  runAttachmentReferenceMigrations,
  rollbackAttachmentReferenceMigration,
  getAttachmentReferenceMigrationStatus,
  DEFAULT_S3_ATTACHMENT_PREFIX,
  DEFAULT_S3_DOWNLOAD_TTL_SECONDS,
  DEFAULT_S3_UPLOAD_TTL_SECONDS,
  MAX_S3_PRESIGN_TTL_SECONDS,
  S3AttachmentBackend,
  S3AttachmentUploadFactory,
  S3AttachmentPrimitives,
  createS3AttachmentBackend,
  createS3AttachmentPrimitives,
  deriveS3AttachmentKey,
  normalizeS3AttachmentPrefix,
  parseAttachmentStorageConfig,
  sha256HexToBase64,
  type AttachmentDatabase,
  type AttachmentHeader,
  type AttachmentBackendHealth,
  type AttachmentBackendKind,
  type AttachmentDownloadOptions,
  type AttachmentDownloadTarget,
  type AttachmentDownloadTargetOptions,
  type AttachmentMetadata,
  type AttachmentResponse,
  type AttachmentSendOptions,
  type AttachmentStatOptions,
  type AttachmentStatus,
  type AttachmentTransportConfig,
  type AttachmentUploadResult,
  type AttachmentTargetHeaders,
  type AttachmentUploadTarget,
  type FilesystemAttachmentBackendConfig,
  type IAttachmentBackend,
  type IAttachmentReader,
  type IAttachmentService,
  type IAttachmentStore,
  type IAttachmentTransport,
  type IAttachmentTransportFactory,
  type IAttachmentUpload,
  type IAttachmentUploadFactory,
  type IReservationStore,
  type ParsedRef,
  type HashFirstReserveAttachmentOptions,
  type UploadFirstReserveAttachmentOptions,
  type Reservation,
  type ReserveAttachmentOptions,
  type AttachmentTransferStage,
  type AttachmentMetadataField,
  validateReserveMetadata,
  type ReserveMetadata,
  type TransportFetchResult,
  type TransportResponse,
  type SwitchboardTransportConfig,
  type SwitchboardClientConfig,
  type AttachmentUploadRequest,
  type AttachmentUploadResponse,
  type AttachmentUploadTransport,
  type XhrUploadTransportOptions,
  type AttachmentBuildResult,
  type AttachmentReferenceIndexBuildResult,
  type AttachmentReferenceInput,
  type AttachmentReferenceMigrationResult,
  type CompiledAttachmentExtractor,
  type IAttachmentReferenceReader,
  type IAttachmentReferenceWriter,
  type IAttachmentSchemaCompiler,
  type AttachmentStorageConfig,
  type S3AttachmentConfig,
  type S3AttachmentBackendDependencies,
  type S3CommandClient,
  type S3Presigner,
} from "./src/index.js";

// Attachment byte movement (multi-reactor W3.4): the browser-capable local
// store, the lazy fetch-on-reference replicator, and the peer-to-peer
// transport over a brokered LocalChannelPort.
export {
  attachmentReferenceAuthorizer,
  AttachmentReplicator,
  collectStream,
  DEFAULT_ATTACHMENT_BACKLOG_PAGE_SIZE,
  DEFAULT_ATTACHMENT_REPLICATION_CONCURRENCY,
  DEFAULT_ATTACHMENT_RETRY_POLICY,
  DEFAULT_IDB_DATABASE,
  DEFAULT_LOCAL_CHUNK_BYTES,
  DEFAULT_LOCAL_REQUEST_TIMEOUT_MS,
  IDB_BLOB_STORE,
  IDB_RECORD_STORE,
  IDB_STATUS_INDEX,
  IdbAttachmentBackend,
  isLocalAttachmentRequest,
  isLocalAttachmentResponse,
  LOCAL_ATTACHMENT_PROTOCOL,
  LocalAttachmentServer,
  LocalAttachmentStore,
  LocalAttachmentTransport,
  MemoryAttachmentBackend,
  SchemaCompiledOperationRefs,
  sha256Hex,
  staticAttachmentReferenceScanner,
  streamFromBytes,
  SYSTEM_REPLICATION_TIMERS,
  type AttachmentReferencePageResult,
  type AttachmentReferenceRow,
  type AttachmentReplicationEntry,
  type AttachmentReplicationState,
  type AttachmentReplicatorOptions,
  type AttachmentReplicatorStatus,
  type AttachmentRetryPolicy,
  type IAttachmentReferenceScanner,
  type IdbAttachmentBackendOptions,
  type ILocalAttachmentBackend,
  type IOperationAttachmentRefs,
  type LocalAttachmentAuthorizer,
  type LocalAttachmentMessage,
  type LocalAttachmentRecord,
  type LocalAttachmentRequest,
  type LocalAttachmentResponse,
  type LocalAttachmentServerOptions,
  type LocalAttachmentTransportOptions,
  type ReplicationTimers,
} from "./src/index.js";
