name: "Chromatic DSPOT"

on:
  push:
    branches:
      - dspot-scalars
  pull_request:
    branches: ["dspot-scalars"]
    types: [opened, synchronize]
  workflow_dispatch:

env:
  NX_ISOLATE_PLUGINS: false

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Build packages
        run: npx nx run-many --target=build --all --skip-nx-cache

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_DSPOT_PROJECT_TOKEN }}
          workingDir: packages/design-system
          exitZeroOnChanges: false # fail on changes
          onlyChanged: true # enable TurboSnap https://www.chromatic.com/docs/turbosnap
