name: 'Chromatic DSPOT'

on:
  push:
    branches:
      - dspot-scalars
  pull_request:
    branches: ['dspot-scalars']
    types: [opened, synchronize]
  workflow_dispatch:

env:
  NX_ISOLATE_PLUGINS: false

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest-8
          run_install: false

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: npx nx run-many --target=build --all --skip-nx-cache

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_DSPOT_PROJECT_TOKEN }}
          workingDir: packages/design-system
