name: Release Cron

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    branches:
      - main
    inputs:
      dry-run:
        type: boolean
        default: false

env:
  NX_ISOLATE_PLUGINS: false

jobs:
  build-and-publish:
    name: Build and Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 10
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set dry run flag
        run: |
          if [[ "${{ inputs.dry-run }}" == "true" ]]; then
            echo "DRY_RUN=true" >> $GITHUB_ENV
          else
            echo "DRY_RUN=false" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Build packages and studio
        run: pnpm nx run-many --target='build' --all --no-cloud
        shell: bash

      - name: Print Environment Info
        run: pnpm nx report
        shell: bash

      - name: git config
        shell: bash
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "-"

      - name: Update pkg version and publish to npm
        run: npx tsx tools/scripts/release.ts --dry-run=${{ env.DRY_RUN }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true 
