// Vendored from activepieces/activepieces@0.91.0 packages/core/piece-types/src/lib/markdown.ts. MIT; see ../../../LICENSE.
// Generated by scripts/sync-upstream.mts — do not edit by hand.
export enum MarkdownVariant {
  BORDERLESS = "BORDERLESS",
  INFO = "INFO",
  WARNING = "WARNING",
  TIP = "TIP",
}
