scalar JSONObject

scalar AttachmentRef

scalar Amount_Tokens

scalar EthereumAddress

scalar Amount_Percentage

scalar EmailAddress

scalar Date

scalar DateTime

scalar URL

scalar Amount_Money

scalar OLabel

scalar Currency

scalar PHID

scalar OID

scalar Amount_Fiat

scalar Amount_Currency

scalar Amount_Crypto

scalar Amount

scalar Upload

type PHOperationContext {
  signer: Signer
}

type Signer {
  user: SignerUser
  app: SignerApp
  signatures: [String!]!
}

type SignerUser {
  address: String!
  networkId: String!
  chainId: Int!
}

type SignerApp {
  name: String!
  key: String!
}

type Operation {
  id: String!
  type: String!
  index: Int!
  timestampUtcMs: DateTime!
  hash: String!
  skip: Int
  inputText: String
  error: String
  context: PHOperationContext
}

interface IDocument {
  id: String!
  name: String!
  documentType: String!
  revision: Int!
  createdAtUtcIso: DateTime!
  lastModifiedAtUtcIso: DateTime!
  operations(first: Int, skip: Int): [Operation!]!
  stateJSON: JSONObject
}

type Todo implements IDocument {
  id: String!
  name: String!
  documentType: String!
  operations(skip: Int, first: Int): [Operation!]!
  revision: Int!
  createdAtUtcIso: DateTime!
  lastModifiedAtUtcIso: DateTime!
  initialState: Todo_TodoState!
  state: Todo_TodoState!
  stateJSON: JSONObject
}

type GqlDocument implements IDocument {
  id: String!
  name: String!
  documentType: String!
  revision: Int!
  createdAtUtcIso: DateTime!
  lastModifiedAtUtcIso: DateTime!
  operations(first: Int, skip: Int): [Operation!]!
  stateJSON: JSONObject
}

type DriveDocument implements IDocument {
  id: String!
  name: String!
  documentType: String!
  revision: Int!
  createdAtUtcIso: DateTime!
  lastModifiedAtUtcIso: DateTime!
  operations(first: Int, skip: Int): [Operation!]!
  stateJSON: JSONObject
}

type Revision {
  scope: String!
  revision: Int!
}

type Todo_PHHashConfig {
  algorithm: String!
  encoding: String!
}

type Todo_PHDocumentScopeState {
  version: Int!
  hash: Todo_PHHashConfig!
  isDeleted: Boolean
  deletedAtUtcIso: String
  deletedBy: String
  deletionReason: String
}

type Todo_FullState {
  auth: JSONObject!
  document: Todo_PHDocumentScopeState!
  global: Todo_TodoState!
  local: JSONObject!
}

input Todo_ViewFilterInput {
  branch: String
  scopes: [String!]
}

input Todo_PagingInput {
  limit: Int
  offset: Int
  cursor: String
}

input Todo_SearchFilterInput {
  parentId: String
  identifiers: [String!]
}

type TodoMutationResult {
  id: String!
  slug: String
  preferredEditor: String
  name: String!
  documentType: String!
  state: Todo_FullState!
  revisionsList: [Revision!]!
  createdAtUtcIso: DateTime!
  lastModifiedAtUtcIso: DateTime!
}

type Todo_DocumentWithChildren {
  document: TodoMutationResult!
  childIds: [String!]!
}

type Todo_DocumentResultPage {
  items: [TodoMutationResult!]!
  totalCount: Int!
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  cursor: String
}

type TodoQueries {
  document(identifier: String!, view: Todo_ViewFilterInput): Todo_DocumentWithChildren
  documents(paging: Todo_PagingInput): Todo_DocumentResultPage!
  findDocuments(search: Todo_SearchFilterInput, view: Todo_ViewFilterInput, paging: Todo_PagingInput): Todo_DocumentResultPage!
  documentOutgoingRelationships(sourceIdentifier: String!, relationshipType: String!, view: Todo_ViewFilterInput, paging: Todo_PagingInput): Todo_DocumentResultPage!
  documentIncomingRelationships(targetIdentifier: String!, relationshipType: String!, view: Todo_ViewFilterInput, paging: Todo_PagingInput): Todo_DocumentResultPage!
}

type TodoMutations {
  createDocument(name: String!, parentIdentifier: String, slug: String, preferredEditor: String, initialState: Todo_InitialStateInput): TodoMutationResult!
  createEmptyDocument(parentIdentifier: String): TodoMutationResult!
  addTodo(docId: PHID!, input: Todo_AddTodoInput!): TodoMutationResult!
  addTodoAsync(docId: PHID!, input: Todo_AddTodoInput!): String!
  removeTodo(docId: PHID!, input: Todo_RemoveTodoInput!): TodoMutationResult!
  removeTodoAsync(docId: PHID!, input: Todo_RemoveTodoInput!): String!
  updateTodo(docId: PHID!, input: Todo_UpdateTodoInput!): TodoMutationResult!
  updateTodoAsync(docId: PHID!, input: Todo_UpdateTodoInput!): String!
  editTitle(docId: PHID!, input: Todo_EditTitleInput!): TodoMutationResult!
  editTitleAsync(docId: PHID!, input: Todo_EditTitleInput!): String!
}

type Query {
  Todo: TodoQueries!
}

type Mutation {
  Todo: TodoMutations!
}

input Todo_TodoStateInput {
  title: String
  todos: [Todo_TodoItemInput]
}

input Todo_TodoItemInput {
  id: String
  title: String
  completed: Boolean
}

input Todo_InitialStateInput {
  global: Todo_TodoStateInput
  local: JSONObject
}

input Todo_AddTodoInput {
  id: String!
  title: String!
  completed: Boolean!
}

input Todo_RemoveTodoInput {
  id: String!
}

input Todo_UpdateTodoInput {
  id: String!
  title: String
  completed: Boolean
}

input Todo_EditTitleInput {
  title: String
}

directive @fixtureTag(name: String!) on OBJECT

scalar Unknown

scalar Address

type Todo_TodoState @fixtureTag(name: "state") {
  title: String
  todos: [Todo_TodoItem!]!
}

type Todo_TodoItem {
  id: String!
  title: String!
  completed: Boolean!
}

extend type Todo_TodoState {
  legacyNote: String
}